import fs from "node:fs"; import path from "node:path"; import pg from "pg";
const REPO="d:/codes/Finance-Management-software";
const env=Object.fromEntries(fs.readFileSync(path.join(REPO,"apps/api/.env"),"utf8").split(/\r?\n/).filter(l=>l&&!l.trim().startsWith("#")&&l.includes("=")).map(l=>{const i=l.indexOf("=");return[l.slice(0,i).trim(),l.slice(i+1).trim().replace(/^["']|["']$/g,"")]}));
const c=new pg.Client({connectionString:env.DATABASE_URL_UNPOOLED||env.DATABASE_URL,ssl:{rejectUnauthorized:false}});
await c.connect();
const q=async(l,s)=>{try{const r=await c.query(s);console.log("##",l);console.table(r.rows);}catch(e){console.log("##",l,"ERR",e.message);}};
await q("runs",`select period_year, period_month, status, count(*)::int as lines, count(*) filter (where l.tds_amount > 0)::int as taxed, coalesce(sum(l.tds_amount),0)::text as tds from payroll_runs r join payroll_lines l on l.payroll_run_id=r.id group by 1,2,3 order by 1,2`);
await q("runs alone",`select period_year, period_month, status from payroll_runs order by 1,2`);
await q("settings",`select fiscal_year_mode, number_format from app_settings`);
await q("counts",`select (select count(*)::int from payroll_runs) runs,(select count(*)::int from payroll_lines) lines,(select count(*)::int from team_members) team,(select count(*)::int from transactions) txns`);
await c.end();
