/**
 * Turn the category tree into the migration that puts it on the live database.
 *
 * The tree lives in apps/api/src/db/seed-categories.ts, and that seeder only
 * ever reaches whatever DATABASE_URL is in front of it — which from a laptop is
 * Neon, not the site. The deploy applies deploy/sql itself, before the
 * containers swap, so writing the same tree as idempotent SQL is how it gets
 * to the live database without anybody SSHing anywhere.
 *
 * Generated rather than typed out, so the two cannot disagree about a name.
 */
import fs from "node:fs";

const src = fs.readFileSync("apps/api/src/db/seed-categories.ts", "utf8");
const start = src.indexOf("const TREE: Group[] = [");
const end = src.indexOf("\n];", start);
const body = src.slice(start, end + 3);

// The file is TypeScript with comments; evaluating the literal is simpler and
// more faithful than parsing it, and it is our own file.
const TREE = new Function(
  body.replace("const TREE: Group[] = [", "return [").replace(/\n\];$/, "\n];"),
)();

/** The same rule as slugify() in packages/shared. */
const slug = (v) =>
  v
    .toLowerCase()
    .trim()
    .replace(/[^\p{L}\p{N}]+/gu, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);

const q = (s) => `'${s.replace(/'/g, "''")}'`;

let out = `-- The starting chart of accounts.
--
-- Written here rather than left to \`npm run db:seed-categories\` because that
-- seeder reaches whatever DATABASE_URL is in front of it, and from a laptop
-- that is Neon — a different database from the live one. The deploy applies
-- this directory to the live database itself, before the containers swap, so
-- this is the path that actually arrives.
--
-- Two levels only. A third dropdown at the moment somebody records a payment
-- reliably produces money filed under the wrong heading.
--
-- Every insert is guarded on (slug, parent), so re-running changes nothing and
-- a heading somebody has renamed is left exactly as they renamed it. Nothing
-- here updates or deletes: this is a starting point, not a fixture.
--
-- Two names are load-bearing. Payroll looks up "Salary" and a TDS challan
-- looks up "TDS deposit", both by name; if either is missing the code falls
-- back to whichever money-out heading sorts first, which is a guess. They can
-- be renamed from Settings — just knowing that is the trade.
--
-- Mirrors TREE in apps/api/src/db/seed-categories.ts. Generated by .gencats.mjs.

`;

TREE.forEach((group, gi) => {
  out += `-- ${group.name}\n`;
  out += `insert into categories (name, slug, kind, color, sort_order, is_system)
select ${q(group.name)}, ${q(slug(group.name))}, ${q(group.kind)}, ${q(group.color)}, ${gi * 10}, true
where not exists (
  select 1 from categories where slug = ${q(slug(group.name))} and parent_id is null
);\n`;

  group.children.forEach((child, ci) => {
    out += `insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select ${q(child)}, ${q(slug(child))}, ${q(group.kind)}, p.id, ${q(group.color)}, ${ci * 10}, true
  from categories p
 where p.slug = ${q(slug(group.name))} and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = ${q(slug(child))} and c.parent_id = p.id
   );\n`;
  });
  out += "\n";
});

fs.writeFileSync("deploy/sql/2026-08-26-categories.sql", out, "utf8");

const total = TREE.reduce((n, g) => n + 1 + g.children.length, 0);
console.log(
  `  ${TREE.length} headings, ${total - TREE.length} sub-categories, ${total} rows\n`,
);
for (const g of TREE) {
  console.log(`  ${g.kind === "in" ? "in " : "out"}  ${g.name.padEnd(22)} ${g.children.join(", ") || "(no sub-categories)"}`);
}
