import fs from "node:fs";import path from "node:path";import jwt from "jsonwebtoken";import pg from "pg";import puppeteer from "puppeteer-core";
const REPO="d:/codes/Finance-Management-software";
const env=Object.fromEntries(fs.readFileSync(path.join(REPO,"apps/api/.env"),"utf8").split(/\r?\n/).filter(l=>l&&!l.trim().startsWith("#")&&l.includes("=")).map(l=>{const i=l.indexOf("=");return [l.slice(0,i).trim(),l.slice(i+1).trim().replace(/^["']|["']$/g,"")];}));
const c=new pg.Client({connectionString:env.DATABASE_URL_UNPOOLED||env.DATABASE_URL,ssl:{rejectUnauthorized:false}});
await c.connect();
const u=(await c.query("select id, role, token_version from users where role='super_admin' and status='active' and deleted_at is null limit 1")).rows[0];
const run=(await c.query("select id from payroll_runs order by period_year desc, period_month desc limit 1")).rows[0];
await c.end();
const token=jwt.sign({sub:u.id,role:u.role,tv:u.token_version}, env.JWT_ACCESS_SECRET,{expiresIn:"2h"});
const chrome="C:/Program Files/Google/Chrome/Application/chrome.exe";
const browser=await puppeteer.launch({executablePath:fs.existsSync(chrome)?chrome:"C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe",headless:"new",args:["--no-sandbox"]});
await browser.setCookie({name:"sfm_access",value:token,domain:"localhost",path:"/"});
const page=await browser.newPage();
await page.setViewport({width:1600,height:1100,deviceScaleFactor:3});
await page.goto("http://localhost:3000/payroll/"+run.id,{waitUntil:"networkidle0",timeout:120000}).catch(()=>{});
await page.evaluate(() => document.fonts.ready);
await new Promise(r=>setTimeout(r,2500));
const box = await page.evaluate(() => {
  const t=document.querySelector(".table-data");
  const ths=[...t.querySelectorAll("thead th")];
  const i=ths.findIndex(h=>h.textContent.trim()==="Net");
  const th=ths[i].getBoundingClientRect();
  const tb=t.getBoundingClientRect();
  return {x:th.left-140, y:tb.top, w:th.width+150, h:200};
});
await page.screenshot({path:process.argv[2], clip:box});
console.log("written");
await browser.close();
