import fs from "node:fs";import path from "node:path";import jwt from "jsonwebtoken";import pg from "pg";import puppeteer from "puppeteer-core";
const REPO="d:/codes/Finance-Management-software";
const env=Object.fromEntries(fs.readFileSync(path.join(REPO,"apps/api/.env"),"utf8").split(/\r?\n/).filter(l=>l&&!l.trim().startsWith("#")&&l.includes("=")).map(l=>{const i=l.indexOf("=");return [l.slice(0,i).trim(),l.slice(i+1).trim().replace(/^["']|["']$/g,"")];}));
const c=new pg.Client({connectionString:env.DATABASE_URL_UNPOOLED||env.DATABASE_URL,ssl:{rejectUnauthorized:false}});
await c.connect();
const {rows}=await c.query("select id, role, token_version from users where role='super_admin' and status='active' and deleted_at is null order by created_at limit 1");
const newest=(await c.query("select tool_name, created_at from subscriptions where deleted_at is null order by created_at desc, id desc limit 3")).rows;
await c.end();
console.log("newest in the database:");
for (const r of newest) console.log("   ", r.tool_name);
const token=jwt.sign({sub:rows[0].id,role:rows[0].role,tv:rows[0].token_version}, env.JWT_ACCESS_SECRET,{expiresIn:"2h"});
const chrome="C:/Program Files/Google/Chrome/Application/chrome.exe";
const browser=await puppeteer.launch({executablePath:fs.existsSync(chrome)?chrome:"C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe",headless:"new",args:["--no-sandbox"]});
await browser.setCookie({name:"sfm_access",value:token,domain:"localhost",path:"/"});
const page=await browser.newPage();
await page.setViewport({width:1600,height:950});
await page.goto("http://localhost:3000/subscriptions",{waitUntil:"networkidle0",timeout:120000}).catch(()=>{});
await new Promise(r=>setTimeout(r,2500));
const out = await page.evaluate(() => {
  const t=document.querySelector(".table-data");
  const heads=[...t.querySelectorAll("thead th")].map(x=>x.textContent.trim());
  const col=heads.indexOf("Tool Name");
  const first=[...t.querySelectorAll("tbody tr")].slice(0,3).map(r=>r.children[col]?.textContent.trim().split("\n")[0]);
  return {first, fx: document.body.innerText.includes("FX locked")};
});
console.log("top three on the page:");
for (const n of out.first) console.log("   ", n);
console.log('"FX locked" still on screen:', out.fx);
await browser.close();
