import fs from "node:fs"; import jwt from "jsonwebtoken"; import pg from "pg"; import puppeteer from "puppeteer-core";
const env=Object.fromEntries(fs.readFileSync("d:/codes/Finance-Management-software/apps/api/.env","utf8").split(/\r?\n/).filter(l=>l&&!l.trim().startsWith("#")&&l.includes("=")).map(l=>{const i=l.indexOf("=");return[l.slice(0,i).trim(),l.slice(i+1).trim().replace(/^["']|["']$/g,"")]}));
const db=new pg.Client({connectionString:env.DATABASE_URL_UNPOOLED||env.DATABASE_URL,ssl:{rejectUnauthorized:false}});
await db.connect();
const {rows:u}=await db.query(`select id, role, token_version from users where status='active' and deleted_at is null order by created_at limit 1`);
const token=jwt.sign({sub:u[0].id, role:u[0].role, tv:u[0].token_version}, env.JWT_ACCESS_SECRET, {expiresIn:"2h"}); await db.end();
const chrome="C:/Program Files/Google/Chrome/Application/chrome.exe", edge="C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe";
const browser=await puppeteer.launch({executablePath: fs.existsSync(chrome)?chrome:edge, headless:"new", args:["--no-sandbox"]});
await browser.setCookie({name:"sfm_access",value:token,domain:"localhost",path:"/"});
const page=await browser.newPage(); const wait=(ms)=>new Promise(r=>setTimeout(r,ms));
const seen=[]; page.on("request",r=>{if(r.url().includes("salary-deductions")) seen.push(r.url().split("?")[1]??"(no query)")});
await page.setViewport({width:1500,height:1000});
await page.goto("http://localhost:3000/tax/withholding",{waitUntil:"networkidle0",timeout:120000}); await wait(900);
const table=()=>page.evaluate(()=>({heading:[...document.querySelectorAll("h2,h3")].map(h=>h.textContent.trim()).join(" / "), tbody:document.querySelector("tbody")?.innerText.replace(/\s+/g," ").trim().slice(0,220)}));
console.log("INITIAL:", JSON.stringify(await table()));
seen.length=0;
await page.evaluate(()=>{const s=[...document.querySelectorAll("select")].find(x=>[...x.options].some(o=>o.textContent.trim()==="July 2026")); const o=[...s.options].find(o=>o.textContent.trim()==="July 2026"); s.value=o.value; s.dispatchEvent(new Event("change",{bubbles:true}));});
await wait(1400);
console.log("AFTER picking July in the Period select -> requests:", JSON.stringify(seen), JSON.stringify(await table()));
seen.length=0;
await page.evaluate(()=>{const s=[...document.querySelectorAll("select")].find(x=>[...x.options].some(o=>o.textContent.trim()==="FY 2025-26")); const o=[...s.options].find(o=>o.textContent.trim()==="FY 2025-26"); s.value=o.value; s.dispatchEvent(new Event("change",{bubbles:true}));});
await wait(1400);
console.log("AFTER picking FY 2025-26 -> requests:", JSON.stringify(seen), JSON.stringify(await table()));
await browser.close();
