import { relations, sql } from "drizzle-orm";
import {
  boolean,
  check,
  date,
  index,
  numeric,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";

import { accounts } from "./accounts";
import { categories } from "./categories";
import {
  fxSourceEnum,
  paymentMethodEnum,
  txnDirectionEnum,
  txnOriginEnum,
} from "./enums";
import { vendors } from "./vendors";

/**
 * The ledger. Every movement of money lives here.
 *
 * Expense Record, the full transaction list, Monthly Bank Stats, and the
 * Monthly Finance Report are four views of this one table. Separate tables
 * would mean every expense needed a matching bank row, and the two drift the
 * first time someone edits one — which is the most common way a small finance
 * system stops agreeing with the bank.
 */
export const transactions = pgTable(
  "transactions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    entityId: uuid("entity_id"),

    /** Human-quotable: TXN-2026-000412. Assigned from a sequence on insert. */
    refNo: text("ref_no").notNull(),

    accountId: uuid("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "restrict" }),

    direction: txnDirectionEnum("direction").notNull(),

    /** The value date — when the money actually moved, not when it was typed. */
    txnDate: date("txn_date").notNull(),

    /** Magnitude only. `direction` carries the sign. */
    amount: numeric("amount", { precision: 14, scale: 2 }).notNull(),

    /**
     * Negative for money out. Generated by Postgres so it cannot disagree with
     * `amount`, and so running balances and net totals are a single window
     * function rather than a CASE repeated in every query.
     */
    signedAmount: numeric("signed_amount", { precision: 14, scale: 2 })
      .notNull()
      .generatedAlwaysAs(
        (): SQLValue =>
          sql`case when ${transactions.direction} = 'in' then ${transactions.amount} else -${transactions.amount} end`,
      ),

    currency: text("currency").notNull().default("BDT"),

    /**
     * When the CEO sends USD, the bank converts and BDT lands. These three keep
     * what was actually sent and the rate actually realised — frozen forever,
     * never re-translated when the rate moves.
     */
    originalAmount: numeric("original_amount", { precision: 14, scale: 2 }),
    originalCurrency: text("original_currency"),
    fxRate: numeric("fx_rate", { precision: 18, scale: 6 }),
    fxRateSource: fxSourceEnum("fx_rate_source"),

    categoryId: uuid("category_id").references(() => categories.id, {
      onDelete: "restrict",
    }),
    vendorId: uuid("vendor_id").references(() => vendors.id, {
      onDelete: "restrict",
    }),
    /** Set when paying a team member; the FK arrives with Phase 5. */
    teamMemberId: uuid("team_member_id"),
    /** Free text when there is no master record for the other party. */
    counterparty: varchar("counterparty", { length: 160 }),

    paymentMethod: paymentMethodEnum("payment_method")
      .notNull()
      .default("bank_transfer"),
    /** Cheque number, bank reference, transaction id. */
    reference: varchar("reference", { length: 120 }),

    description: text("description").notNull(),
    notes: text("notes"),

    /** Google Drive link. The app stores the link, never the file. */
    receiptUrl: text("receipt_url"),

    /**
     * When tax was withheld: the gross bill and the amount kept back.
     * `amount` remains what actually left the account.
     */
    billAmount: numeric("bill_amount", { precision: 14, scale: 2 }),
    withheldTaxAmount: numeric("withheld_tax_amount", {
      precision: 14,
      scale: 2,
    })
      .notNull()
      .default("0"),

    /** How the row got here — manual, import, AI, payroll, tax payment. */
    /**
     * What a dollar was worth on the day, captured when the entry was made.
     *
     * Separate from `fx_rate`, which is the rate a conversion *actually*
     * happened at. This one is a reference: it is what turns a taka figure
     * into a readable dollar figure on the statement, and it has to be the
     * rate of that day rather than of the day somebody runs the report.
     */
    usdRate: numeric("usd_rate", { precision: 18, scale: 6 }),

    createdVia: txnOriginEnum("created_via").notNull().default("manual"),

    /** Explicit provenance rather than a polymorphic pointer. */
    payrollRunId: uuid("payroll_run_id"),
    payrollLineId: uuid("payroll_line_id"),
    taxPaymentId: uuid("tax_payment_id"),

    /** Two rows — one out, one in — share this when money moves internally. */
    transferGroupId: uuid("transfer_group_id"),

    /** Bank statement line id, so a re-import can recognise its own rows. */
    externalRef: text("external_ref"),

    /**
     * Fingerprint for import duplicate warnings. Not unique — two identical
     * payments on one day are legitimate — but a match is worth flagging.
     *
     * Written by the service rather than generated by Postgres: casting a date
     * to text depends on the DateStyle setting, which makes the expression
     * STABLE rather than IMMUTABLE, and Postgres refuses that in a generated
     * column. `dedupeKey()` in transactions.service.ts is the one place it is
     * computed.
     */
    dedupeHash: text("dedupe_hash"),

    /** Hook for real bank reconciliation later. */
    isStatementMatched: boolean("is_statement_matched")
      .notNull()
      .default(false),
    importBatchId: uuid("import_batch_id"),

    /**
     * Money rows are voided, never deleted. A deleted row cannot answer the
     * question someone asks about it six months later.
     */
    voidedAt: timestamp("voided_at", { withTimezone: true }),
    voidedBy: uuid("voided_by"),
    voidReason: text("void_reason"),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    createdBy: uuid("created_by"),
    updatedBy: uuid("updated_by"),
  },
  (t) => [
    uniqueIndex("transactions_ref_idx").on(t.refNo),

    // The register: one account, newest first.
    index("transactions_register_idx").on(t.accountId, t.txnDate, t.id),
    index("transactions_date_idx").on(t.txnDate),
    index("transactions_category_idx").on(t.categoryId, t.txnDate),
    index("transactions_vendor_idx").on(t.vendorId),
    index("transactions_direction_idx").on(t.direction, t.txnDate),
    index("transactions_dedupe_idx").on(t.dedupeHash),
    index("transactions_transfer_idx").on(t.transferGroupId),
    index("transactions_batch_idx").on(t.importBatchId),

    check("transactions_amount_positive", sql`${t.amount} > 0`),
    check(
      "transactions_withheld_not_negative",
      sql`${t.withheldTaxAmount} >= 0`,
    ),
    // A foreign amount is meaningless without the rate that converted it.
    check(
      "transactions_fx_complete",
      sql`(${t.originalCurrency} is null and ${t.originalAmount} is null and ${t.fxRate} is null)
          or (${t.originalCurrency} is not null and ${t.originalAmount} is not null and ${t.fxRate} is not null)`,
    ),
  ],
);

/** Drizzle's generated-column callback wants a SQL expression. */
type SQLValue = ReturnType<typeof sql>;

export const transactionsRelations = relations(transactions, ({ one }) => ({
  account: one(accounts, {
    fields: [transactions.accountId],
    references: [accounts.id],
  }),
  category: one(categories, {
    fields: [transactions.categoryId],
    references: [categories.id],
  }),
  vendor: one(vendors, {
    fields: [transactions.vendorId],
    references: [vendors.id],
  }),
}));

export type Transaction = typeof transactions.$inferSelect;
export type NewTransaction = typeof transactions.$inferInsert;
