-- The starting chart of accounts.
--
-- Written here rather than left to `npm run db:seed-categories` because that
-- seeder reaches whatever DATABASE_URL is in front of it, and from a laptop
-- that is Neon — a different database from the live one. The deploy applies
-- this directory to the live database itself, before the containers swap, so
-- this is the path that actually arrives.
--
-- Two levels only. A third dropdown at the moment somebody records a payment
-- reliably produces money filed under the wrong heading.
--
-- Every insert is guarded on (slug, parent), so re-running changes nothing and
-- a heading somebody has renamed is left exactly as they renamed it. Nothing
-- here updates or deletes: this is a starting point, not a fixture.
--
-- Two names are load-bearing. Payroll looks up "Salary" and a TDS challan
-- looks up "TDS deposit", both by name; if either is missing the code falls
-- back to whichever money-out heading sorts first, which is a guess. They can
-- be renamed from Settings — just knowing that is the trade.
--
-- Mirrors TREE in apps/api/src/db/seed-categories.ts. Generated by .gencats.mjs.

-- Office & premises
insert into categories (name, slug, kind, color, sort_order, is_system)
select 'Office & premises', 'office-premises', 'out', '#4f46e5', 0, true
where not exists (
  select 1 from categories where slug = 'office-premises' and parent_id is null
);
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Office rent', 'office-rent', 'out', p.id, '#4f46e5', 0, true
  from categories p
 where p.slug = 'office-premises' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'office-rent' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Electricity', 'electricity', 'out', p.id, '#4f46e5', 10, true
  from categories p
 where p.slug = 'office-premises' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'electricity' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Water & gas', 'water-gas', 'out', p.id, '#4f46e5', 20, true
  from categories p
 where p.slug = 'office-premises' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'water-gas' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Internet', 'internet', 'out', p.id, '#4f46e5', 30, true
  from categories p
 where p.slug = 'office-premises' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'internet' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Cleaning & maintenance', 'cleaning-maintenance', 'out', p.id, '#4f46e5', 40, true
  from categories p
 where p.slug = 'office-premises' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'cleaning-maintenance' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Security', 'security', 'out', p.id, '#4f46e5', 50, true
  from categories p
 where p.slug = 'office-premises' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'security' and c.parent_id = p.id
   );

-- People
insert into categories (name, slug, kind, color, sort_order, is_system)
select 'People', 'people', 'out', '#0ea5e9', 10, true
where not exists (
  select 1 from categories where slug = 'people' and parent_id is null
);
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Salary', 'salary', 'out', p.id, '#0ea5e9', 0, true
  from categories p
 where p.slug = 'people' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'salary' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Bonus', 'bonus', 'out', p.id, '#0ea5e9', 10, true
  from categories p
 where p.slug = 'people' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'bonus' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Festival bonus', 'festival-bonus', 'out', p.id, '#0ea5e9', 20, true
  from categories p
 where p.slug = 'people' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'festival-bonus' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Overtime', 'overtime', 'out', p.id, '#0ea5e9', 30, true
  from categories p
 where p.slug = 'people' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'overtime' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Provident fund', 'provident-fund', 'out', p.id, '#0ea5e9', 40, true
  from categories p
 where p.slug = 'people' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'provident-fund' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Leave encashment', 'leave-encashment', 'out', p.id, '#0ea5e9', 50, true
  from categories p
 where p.slug = 'people' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'leave-encashment' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Contractor payment', 'contractor-payment', 'out', p.id, '#0ea5e9', 60, true
  from categories p
 where p.slug = 'people' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'contractor-payment' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Recruitment', 'recruitment', 'out', p.id, '#0ea5e9', 70, true
  from categories p
 where p.slug = 'people' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'recruitment' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Training', 'training', 'out', p.id, '#0ea5e9', 80, true
  from categories p
 where p.slug = 'people' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'training' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Staff welfare', 'staff-welfare', 'out', p.id, '#0ea5e9', 90, true
  from categories p
 where p.slug = 'people' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'staff-welfare' and c.parent_id = p.id
   );

-- Technology
insert into categories (name, slug, kind, color, sort_order, is_system)
select 'Technology', 'technology', 'out', '#0d9488', 20, true
where not exists (
  select 1 from categories where slug = 'technology' and parent_id is null
);
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Software & subscriptions', 'software-subscriptions', 'out', p.id, '#0d9488', 0, true
  from categories p
 where p.slug = 'technology' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'software-subscriptions' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'AI tools', 'ai-tools', 'out', p.id, '#0d9488', 10, true
  from categories p
 where p.slug = 'technology' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'ai-tools' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Hosting & servers', 'hosting-servers', 'out', p.id, '#0d9488', 20, true
  from categories p
 where p.slug = 'technology' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'hosting-servers' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Domains', 'domains', 'out', p.id, '#0d9488', 30, true
  from categories p
 where p.slug = 'technology' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'domains' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Hardware & equipment', 'hardware-equipment', 'out', p.id, '#0d9488', 40, true
  from categories p
 where p.slug = 'technology' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'hardware-equipment' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Development & maintenance', 'development-maintenance', 'out', p.id, '#0d9488', 50, true
  from categories p
 where p.slug = 'technology' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'development-maintenance' and c.parent_id = p.id
   );

-- Marketing
insert into categories (name, slug, kind, color, sort_order, is_system)
select 'Marketing', 'marketing', 'out', '#d97706', 30, true
where not exists (
  select 1 from categories where slug = 'marketing' and parent_id is null
);
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Advertising', 'advertising', 'out', p.id, '#d97706', 0, true
  from categories p
 where p.slug = 'marketing' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'advertising' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Content & design', 'content-design', 'out', p.id, '#d97706', 10, true
  from categories p
 where p.slug = 'marketing' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'content-design' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Agency & freelancers', 'agency-freelancers', 'out', p.id, '#d97706', 20, true
  from categories p
 where p.slug = 'marketing' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'agency-freelancers' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Sponsorship', 'sponsorship', 'out', p.id, '#d97706', 30, true
  from categories p
 where p.slug = 'marketing' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'sponsorship' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Events', 'events', 'out', p.id, '#d97706', 40, true
  from categories p
 where p.slug = 'marketing' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'events' and c.parent_id = p.id
   );

-- Administrative
insert into categories (name, slug, kind, color, sort_order, is_system)
select 'Administrative', 'administrative', 'out', '#db2777', 40, true
where not exists (
  select 1 from categories where slug = 'administrative' and parent_id is null
);
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Professional fees', 'professional-fees', 'out', p.id, '#db2777', 0, true
  from categories p
 where p.slug = 'administrative' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'professional-fees' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Legal & compliance', 'legal-compliance', 'out', p.id, '#db2777', 10, true
  from categories p
 where p.slug = 'administrative' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'legal-compliance' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Government fees & licences', 'government-fees-licences', 'out', p.id, '#db2777', 20, true
  from categories p
 where p.slug = 'administrative' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'government-fees-licences' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Bank charges', 'bank-charges', 'out', p.id, '#db2777', 30, true
  from categories p
 where p.slug = 'administrative' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'bank-charges' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Insurance', 'insurance', 'out', p.id, '#db2777', 40, true
  from categories p
 where p.slug = 'administrative' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'insurance' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Office supplies', 'office-supplies', 'out', p.id, '#db2777', 50, true
  from categories p
 where p.slug = 'administrative' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'office-supplies' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Courier & postage', 'courier-postage', 'out', p.id, '#db2777', 60, true
  from categories p
 where p.slug = 'administrative' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'courier-postage' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Repairs & servicing', 'repairs-servicing', 'out', p.id, '#db2777', 70, true
  from categories p
 where p.slug = 'administrative' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'repairs-servicing' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Travel & transport', 'travel-transport', 'out', p.id, '#db2777', 80, true
  from categories p
 where p.slug = 'administrative' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'travel-transport' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Food & hospitality', 'food-hospitality', 'out', p.id, '#db2777', 90, true
  from categories p
 where p.slug = 'administrative' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'food-hospitality' and c.parent_id = p.id
   );

-- Tax
insert into categories (name, slug, kind, color, sort_order, is_system)
select 'Tax', 'tax', 'out', '#7c3aed', 50, true
where not exists (
  select 1 from categories where slug = 'tax' and parent_id is null
);
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'TDS deposit', 'tds-deposit', 'out', p.id, '#7c3aed', 0, true
  from categories p
 where p.slug = 'tax' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'tds-deposit' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'VAT', 'vat', 'out', p.id, '#7c3aed', 10, true
  from categories p
 where p.slug = 'tax' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'vat' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Withholding VAT', 'withholding-vat', 'out', p.id, '#7c3aed', 20, true
  from categories p
 where p.slug = 'tax' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'withholding-vat' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Advance tax', 'advance-tax', 'out', p.id, '#7c3aed', 30, true
  from categories p
 where p.slug = 'tax' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'advance-tax' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Income tax', 'income-tax', 'out', p.id, '#7c3aed', 40, true
  from categories p
 where p.slug = 'tax' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'income-tax' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Customs & duty', 'customs-duty', 'out', p.id, '#7c3aed', 50, true
  from categories p
 where p.slug = 'tax' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'customs-duty' and c.parent_id = p.id
   );

-- Finance
insert into categories (name, slug, kind, color, sort_order, is_system)
select 'Finance', 'finance', 'out', '#b45309', 60, true
where not exists (
  select 1 from categories where slug = 'finance' and parent_id is null
);
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Loan repayment', 'loan-repayment', 'out', p.id, '#b45309', 0, true
  from categories p
 where p.slug = 'finance' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'loan-repayment' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Interest paid', 'interest-paid', 'out', p.id, '#b45309', 10, true
  from categories p
 where p.slug = 'finance' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'interest-paid' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Exchange loss', 'exchange-loss', 'out', p.id, '#b45309', 20, true
  from categories p
 where p.slug = 'finance' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'exchange-loss' and c.parent_id = p.id
   );

-- Other expenses
insert into categories (name, slug, kind, color, sort_order, is_system)
select 'Other expenses', 'other-expenses', 'out', '#5b6472', 70, true
where not exists (
  select 1 from categories where slug = 'other-expenses' and parent_id is null
);

-- Money in
insert into categories (name, slug, kind, color, sort_order, is_system)
select 'Money in', 'money-in', 'in', '#047857', 80, true
where not exists (
  select 1 from categories where slug = 'money-in' and parent_id is null
);
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'CEO funding', 'ceo-funding', 'in', p.id, '#047857', 0, true
  from categories p
 where p.slug = 'money-in' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'ceo-funding' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Client receipts', 'client-receipts', 'in', p.id, '#047857', 10, true
  from categories p
 where p.slug = 'money-in' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'client-receipts' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Loan received', 'loan-received', 'in', p.id, '#047857', 20, true
  from categories p
 where p.slug = 'money-in' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'loan-received' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Investment received', 'investment-received', 'in', p.id, '#047857', 30, true
  from categories p
 where p.slug = 'money-in' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'investment-received' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Interest income', 'interest-income', 'in', p.id, '#047857', 40, true
  from categories p
 where p.slug = 'money-in' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'interest-income' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Exchange gain', 'exchange-gain', 'in', p.id, '#047857', 50, true
  from categories p
 where p.slug = 'money-in' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'exchange-gain' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Refunds', 'refunds', 'in', p.id, '#047857', 60, true
  from categories p
 where p.slug = 'money-in' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'refunds' and c.parent_id = p.id
   );
insert into categories (name, slug, kind, parent_id, color, sort_order, is_system)
select 'Other income', 'other-income', 'in', p.id, '#047857', 70, true
  from categories p
 where p.slug = 'money-in' and p.parent_id is null
   and not exists (
     select 1 from categories c where c.slug = 'other-income' and c.parent_id = p.id
   );

